---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngin
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ngin
  template:
    metadata:
      labels:
        app: ngin
    spec:
      containers:
        - name: ngin
          image: gcr.io/qwiklabs-gcp-03-5ba82fbc2dca/vitcuka:latest
          ports:
            - containerPort: 80
